# Markdown

Tipos de encabezado

   # Encabezado de nivel 1
   ## Encabezado de nivel  2
   ### Encabezado de nivel  3
   #### Encabezado de nivel  4
   ##### Encabezado de nivel  5
   ###### Encabezado de nivel  6

Cursiva y negrita

Se usan los simbolos (\-) y (\*) de la siguiente manera:

>+ *Texto en cursiva*
>+ _Texto en cursiva_
>+ **Texto en negrita**
>+ __Texto en negrita__
>+ ***Texto en cursiva y negrita***
>+ ___Texto en cursiva y negrita___

Sangrías:
>Este en un ejemplo de sangría.
>>Este en un ejemplo de sangría.
>>>Este en un ejemplo de sangría.

Resaltado

<mark>Este texto está resaltado</mark>

# Asignación de variables

In [ ]:
mi_variable = 9

1. El nombre de la variable es : "mi_variable"
2. El símbolo "=" es un operador de asignación
3. El valor de la variable es "3"

In [ ]:
mi_variable

9

# Tipos de variables

**1. Integer**

In [ ]:
edad = 35
type(edad)

int

**2. Float**

In [ ]:
salario = 1250.90
type(salario)

float

**3. Complex**

In [ ]:
resultado = 6+3j
resultado

(6+3j)

In [ ]:
resultado = 4+3j

# Seleccionamos las partes del número complejo
print("La parte real es:", resultado.real)
print("La parte imaginaria es:", resultado.imag)

La parte real es: 4.0
La parte imaginaria es: 3.0

**4. Booleano**

In [ ]:
booleano1 = True
booleano2 = False
type(booleano1)

bool

In [ ]:
False + False

0

*Considerar: Los tipo de variables booleanos se comportan como un número entero.*

# Operadores numéricos

**1. Suma**

In [ ]:
cant1 = 30
cant2 = 40
print(cant1+cant2)

70

**2. Resta**

In [ ]:
cant1 = 30
cant2 = 40
print(cant1-cant2)

-10

**3. Multiplicación**

In [ ]:
cant1 = 30
cant2 = 40
print(cant1*cant2)

1200

**4. División**

In [ ]:
cant1 = 30
cant2 = 7
print(cant1/cant2)

4.285714285714286

**5. División entera**

In [ ]:
cant1 = 30
cant2 = 7
print(cant1//cant2)

4

**6. Módulo**

In [ ]:
cant1 = 30
cant2 = 7
print(cant1%cant2)

2

**7. Exponente**

In [ ]:
cant1 = 30
cant2 = 2
print(cant1**cant2)

900

In [ ]:
cant1 = 30
cant2 = 2
print(pow(cant1,cant2))

900

# Operadores relacionales

**1. Igual que**

In [ ]:
1 == 1

True

**2. Distinto que**

In [ ]:
1 != 1

False

**3. Menor y menor igual que**

In [ ]:
print(1<1)
print(1<=1)

False
True

**4. Mayor y mayor igual que**

In [ ]:
print(1>1)
print(1>=1)

False
True

**5. Is y is not**

In [ ]:
a = 1
b = 2

print(a is b)
print(a is not b)

False
True

# Operadores lógicos

**1. And**

In [ ]:
print(True and True)
print(True and False)
print(False and True)
print(False and False)

True
False
False
False

In [ ]:
edad = 20
peso = 50

if edad > 18 and peso > 60:    # True and False - False
    print("Apto")
else:
    print("No apto")

No apto

**2. Or**

In [ ]:
print(True or True)
print(True or False)
print(False or True)
print(False or False)

True
True
True
False

In [ ]:
edad = 20
peso = 50

if edad > 18 or peso > 60:    # True or False - True
    print("Apto")
else:
    print("No apto")

Apto

**3. Not**

In [ ]:
print(not True)
print(not False)

False
True

# Sentencias de control

__if,elif,else__: La instrucción `if` es uno de los tipos de instrucciones de flujo de control más conocidos. Comprueba una condición que, si es cierta (se evalúa a `True`),continuará la ejecución con el código del bloque. Una instrucción `if` puede ir seguida opcionalmente por uno o más bloques `elif` y un bloque final `else` que se sólo evalúa si todas las condiciones anteriores han sido falsas (evaluadas a `False`). Si alguna de las condiciones se evalúa a `True`, no se alcanzarán los bloques `elif` o `else` posteriores.

In [ ]:
x = 4
if x < 0:
   print('Es negativo')
elif x == 0:
   print('Igual a cero')
elif 0 < x < 5:
   print('Positivo pero menor que 5')
else:
   print('Positivo y mayor o igual a 5')

Positivo pero menor que 5

__Ejemplo:__ En un club de fans solo se permite la entrada a personas que tengan por lo menos 16 años. Se necesita crear una sentencia de control condicional que imprima "No aceptado" cuando el postulante no cumple con la edad mínima requerida y en caso contrario que se muestre " Aceptado".

In [ ]:
edad = -80
if edad >=16:
        print("Aceptado")
else:
        print("No Aceptado")

No Aceptado

In [ ]:
edad = 1000
if edad > 0 and edad <100:
    if edad >=16:
        print("Aceptado")
    else:
        print("No Aceptado")
else:
    print("Por favor colocar edades verdaderas")

Por favor colocar edades verdaderas

__Bucle for__: Los bucles `for` permiten iterar sobre una colección (como una *lista* o *tupla*) o un *iterador*. La sintaxis estándar para un bucle `for` es:

In [ ]:
nombres = ["Carlos","Sandra","Verónica","Samuel","Pedro"]
for i in nombres[2:]:
    print(i)

Verónica
Samuel
Pedro

__Ejemplo__: Mostrar los múltiplos de 5 hasta el número 50

In [ ]:
for i in range(5,51,5):
  print(i)

5
10
15
20
25
30
35
40
45
50

__Bucle While__: Un bucle `while` especifica una condición y un bloque de código que se ejecutará hasta que la condición se evalúe como `False`.

In [ ]:
x = 256
total = 0
while x > 0:
    total += x # total = total + x        #1 iter : total = 0+256 = 256  # 2da iter: total = 256+255
    x = x - 1                             #1 iter: x = 256-1 = 255       # 2da iter: x = 255-1 = 254

# Funciones

In [ ]:
def Mi_funcion(x, y, z):
  # Multiplica/divide z por la suma de x e y en función del valor de z
  if z > 1:
      return z * (x + y)  # 3*(1+2)
  else:
      return z / (x + y)  # 0.5/(1+2)

In [ ]:
Mi_funcion(1,3,5)

20

# Listas

In [ ]:
lista1 = [1,2,"a",True,[3,4]]
lista2 = [x for x in range(0,2)]
lista3 = list(range(0,2))

In [ ]:
# Utilizamos de ejemplo la lista 1
lista1

[1, 2, 'a', True, [3, 4]]

In [ ]:
# Accediendo al primer elemento de la lista 1
lista1[3]

True

In [ ]:
# Modificando el primer elemento de la lista 1
lista1[0] = 4

In [ ]:
# Concatenando listas
lista_concatenada = lista1+lista2
lista_concatenada

[4, 2, 'a', True, [3, 4], 0, 1]

In [ ]:
# Acceso a los elementos de una lista dentro de otra lista
una_lista = list(['foo', [1, 2], True])
una_lista[1][1]

2

# Arrays

In [ ]:
import numpy as np

In [ ]:
# Array unidimensional:
array_uni = np.array([1,2,3])
array_uni

array([1, 2, 3])

In [ ]:
# Dimensión del array
print("La dimensión del array es: ", array_uni.ndim)
# Tamaño del array
print("EL tamaño del array es: ", array_uni.size)

La dimensión del array es:  1
EL tamaño del array es:  3

In [ ]:
# Array bidimensional: n x unidimensional
array_bi = np.array([[1,2,3],[4,5,6],[7,8,9]])
array_bi

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
# Dimensión del array
print("La dimensión del array es: ", array_bi.ndim)
# Tamaño del array
print("EL tamaño del array es: ", array_bi.size)

La dimensión del array es:  2
EL tamaño del array es:  9

In [ ]:
# Array tridimensional n x (filas x columnas)
array_tri = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
array_tri

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [ ]:
# Dimensión del array
print("La dimensión del array es: ", array_tri.ndim)
# Tamaño del array
print("EL tamaño del array es: ", array_tri.size)

La dimensión del array es:  3
EL tamaño del array es:  12

In [ ]:
array_uni

array([1, 2, 3])

In [ ]:
# Accediendo a los elementos de un array unidimensional
array_uni[0]

np.int64(1)

In [ ]:
array_bi

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
# Accediendo a los elementos de un array bidimensional
array_bi[1][1]

np.int64(5)

In [ ]:
array_tri

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [ ]:
# Accediendo a los elementos de un array tridimensional 8
array_tri[0][1][1]

np.int64(5)

In [ ]:
array_uni

array([1, 2, 3])

In [ ]:
# Sacando la media de los valores de un array univariado
array_uni.mean()

np.float64(2.0)

In [ ]:
array_bi

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
# Sacando la media de los valores de un array bivariado
array_bi.mean()

np.float64(5.0)

In [ ]:
# Sacando la suma de los valores de un array bivariado
array_bi.sum()

np.int64(45)

In [ ]:
array_bi

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
import math as m

In [ ]:
# Sacando el cuadrado a los elementos de un array bivariado
np.square(array_bi)

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [ ]:
# Sacando la raíz cuadrada a los elementos de un array bivariado
np.sqrt(array_bi)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [ ]:
# Sacando la exponencial a los elementos de un array bivariado
np.exp(array_bi)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02],
       [1.09663316e+03, 2.98095799e+03, 8.10308393e+03]])

In [ ]:
# Sacando el logaritmo a los elementos de un array bivariado
np.log(array_bi)

array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947],
       [1.94591015, 2.07944154, 2.19722458]])

In [ ]:
array_bi

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
# Ejemplo 1: ¿Cómo hago para calcular la suma y media solo de la primera fila del array 2D?
array_bi[0].sum()

np.int64(6)

In [ ]:
# Ejemplo 2: ¿Cómo hago para calcular la suma y media solo de la primera columna del array 2D?
array_bi.T[0].mean()

np.float64(4.0)

In [ ]:
# Ejemplo 3: ¿Cómo hago para calcular el logaritmo de la primera fila del array 2D?
np.log(array_bi[0])

array([0.        , 0.69314718, 1.09861229])

# Series

In [ ]:
import pandas as pd

In [ ]:
# Creacion de un objeto Series
notas_mate = pd.Series([5, 14, 16, 8, 10], index = ["Pedro", "Ana", "Julian", "Norma","Paul"])
notas_mate

Pedro      5
Ana       14
Julian    16
Norma      8
Paul      10
dtype: int64

In [ ]:
# Creacion de un objeto Series con sus respectivos índices
notas_mate = pd.Series([5, 14, 16, 8, 10], index = ["Santiago","Pedro","Julia","Ana","Alberto"])
notas_mate

Santiago     5
Pedro       14
Julia       16
Ana          8
Alberto     10
dtype: int64

In [ ]:
# Creación de un objeto Series inicializandolo con un escalar
pd.Series(15, ["test1", "test2", "test3"])

test1    15
test2    15
test3    15
dtype: int64

In [ ]:
notas_mate

Santiago     5
Pedro       14
Julia       16
Ana          8
Alberto     10
dtype: int64

In [ ]:
# Accediendo al tercer elemento del objeto por índice
notas_mate["Julia"]

np.int64(16)

In [ ]:
# Accediendo al tercer elemento del objeto por indice con loc
notas_mate.loc["Julia"]

np.int64(16)

In [ ]:
# Accediendo al tercer elemento del objeto por posición
notas_mate[2]

/tmp/ipykernel_2080/1047763014.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  notas_mate[2]

np.int64(16)

In [ ]:
# Accediendo al tercer elemento del objeto por posición con iloc
notas_mate.iloc[2]

np.int64(16)

In [ ]:
# Accediendo al tercer y cuarto elemento de la serie (Forma manual)
notas_mate[["Julia","Ana"]]

Julia    16
Ana       8
dtype: int64

In [ ]:
# Sacando la media a las notas de matematica
notas_mate.mean()

np.float64(10.6)

In [ ]:
# Sacando la máxima nota de matermática
notas_mate.max()

16

In [ ]:
nuevo_registro = pd.Series([19,14,20,10], index = ["Jorge","Luis","Ana","Luisa"])
nuevo_registro

Jorge    19
Luis     14
Ana      20
Luisa    10
dtype: int64

In [ ]:
notas_mate

Santiago     5
Pedro       14
Julia       16
Ana          8
Alberto     10
dtype: int64

In [ ]:
# Agregamos nuevos registros a nuestra Serie de notas
nuevo_registro = pd.Series([19,14,20,10], index = ["Jorge","Luis","Ana","Luisa"])
pd.concat([notas_mate, nuevo_registro])

Santiago     5
Pedro       14
Julia       16
Ana          8
Alberto     10
Jorge       19
Luis        14
Ana         20
Luisa       10
dtype: int64

# Data Frames

In [ ]:
import numpy as np
np.array([[50,60],[20,23]])

array([[50, 60],
       [20, 23]])

In [ ]:
# Creación de un dataframe iniciándolo con un array
pd.DataFrame(np.array([[50,60],[20,23]]),columns = ["Pesos","Edades"])

   Pesos  Edades
0     50      60
1     20      23

In [ ]:
notas_mate

Santiago     5
Pedro       14
Julia       16
Ana          8
Alberto     10
dtype: int64

In [ ]:
# Creación de un dataframe iniciándolo con una serie
pd.DataFrame(notas_mate, columns = ["Notas"])

          Notas
Santiago      5
Pedro        14
Julia        16
Ana           8
Alberto      10

In [ ]:
# Creación de un DataFrame inicializándolo con una lista de listas de Python
# Importante: Deben especificarse las columnas e indices por separado
valores = [
    [185, 4, 76],
    [170, 0, 65],
    [190, 1, 89]
]

df = pd.DataFrame(
        valores,
        columns = ["altura", "hijos", "peso"],
        index = ["Pedro", "Ana", "Juan"])
df

       altura  hijos  peso
Pedro     185      4    76
Ana       170      0    65
Juan      190      1    89

In [ ]:
# Accediendo a la columna altura
df["altura"]

Pedro    185
Ana      170
Juan     190
Name: altura, dtype: int64

In [ ]:
# Reto: ¿Cómo puedo acceder a la altura de Pedro por posición?
df["altura"].iloc[0]

np.int64(185)

In [ ]:
# Reto: ¿Cómo puedo acceder a la altura de Pedro por índice?
df["altura"].loc["Pedro"]

np.int64(185)

In [ ]:
# Accediendo a las columnas altura y peso
df[["altura","peso"]]

       altura  peso
Pedro     185    76
Ana       170    65
Juan      190    89

In [ ]:
# Filtros
df[df["hijos"]>3]

       altura  hijos  peso
Pedro     185      4    76

In [ ]:
# Podemos añadir una columna: En base al peso y altura calcular el IMC de cada persona
df["IMC"] = df["peso"]/df["altura"]**2
df

       altura  hijos  peso       IMC
Pedro     185      4    76  0.002221
Ana       170      0    65  0.002249
Juan      190      1    89  0.002465

In [ ]:
# Podemos añadir una columna: En base al peso y altura calcular el IMC de cada persona
df["altura"] = df["peso"]/df["altura"]**2
df

         altura  hijos  peso       IMC
Pedro  0.002221      4    76  0.002221
Ana    0.002249      0    65  0.002249
Juan   0.002465      1    89  0.002465

In [ ]:
df

         altura  hijos  peso       IMC
Pedro  0.002221      4    76  0.002221
Ana    0.002249      0    65  0.002249
Juan   0.002465      1    89  0.002465

In [ ]:
# Podemos eliminar una columna: Elimina la columna de IMC
df.drop(columns = ["hijos"], inplace = True)
df

         altura  peso       IMC
Pedro  0.002221    76  0.002221
Ana    0.002249    65  0.002249
Juan   0.002465    89  0.002465

In [ ]:
del df

In [ ]:
df

NameError: name 'df' is not defined

In [ ]:
# Guardar y cargar un dataframe
df.to_excel("df_personas.xlsx")
df.to_csv("df_personas.csv")
df.to_html("df_personas.html")
df.to_json("df_personas.json")

# Directorio

In [ ]:
import os

In [ ]:
# Directorio de trabajo
os.getcwd()

'/content'

In [ ]:
# Cambiar directorio de trabajo
os.chdir("/boot")

In [ ]:
os.getcwd()

'/boot'

In [ ]:
# Cargar el DataFrame en Jupyter
df2 = pd.read_csv("/content/df_personas.csv")
df2

  Unnamed: 0  altura  hijos  peso
0      Pedro     185      4    76
1        Ana     170      0    65
2       Juan     190      1    89

In [ ]:
# Cargar el DataFrame con la primera columna correctamente asignada
df2 = pd.read_csv("/content/df_personas.csv",index_col=0)
df2

       altura  hijos  peso
Pedro     185      4    76
Ana       170      0    65
Juan      190      1    89